### PR TITLE
fix tooltip bug

### LINKED ISSUE #253: Subject: Tooltip is hidden when the mouse is at the bottom
screen shot 2017-09-18 at 15 45 22

### PR DESCRIPTION
**Pull request by mpgxvii**
Closes #253

### CODE REVIEW

File: src/app/components/source-graphs/source-graphs.component.ts [hunk 1]
```diff
@@ -54,9 +55,15 @@ export class SourceGraphsComponent implements OnInit {
...
-      this.tooltipY = event.clientY
+      this.tooltipY =
+        event.clientY < document.body.clientHeight - this.tooltip.height
+          ? event.clientY
+          : document.body.clientHeight -
+            this.tooltip.height -
+            this.tooltipOffsetY
       this.lineX = event.layerX
       this.tooltipShow = 1
+      this.lineX = event.layerX + 8
```
Comment (herkulano) [inline src/app/components/source-graphs/source-graphs.component.ts]: duplicate of https://github.com/RADAR-CNS/RADAR-Dashboard/pull/254/files#diff-07b51894df76f210fb2a7259f865741eR64

File: src/app/components/source-graphs/source-graphs.component.ts [hunk 2]
```diff
@@ -54,9 +55,15 @@ export class SourceGraphsComponent implements OnInit {
           ? event.clientX - this.tooltip.mid
           : document.body.clientWidth - this.tooltip.width
 
-      this.tooltipY = event.clientY
+      this.tooltipY =
+        event.clientY < document.body.clientHeight - this.tooltip.height
+          ? event.clientY
+          : document.body.clientHeight -
```
Comment (herkulano) [inline src/app/components/source-graphs/source-graphs.component.ts]: the tooltip needs to be above the mouse when the mouse is at the bottom

File: src/app/components/source-graphs/source-tooltip/source-tooltip.component.ts [hunk 3]
```diff
@@ -44,6 +44,10 @@ export class SourceTooltipComponent implements AfterViewInit {
 
   constructor(private element: ElementRef) {}
 
+  public get height(): number {
```
Comment (herkulano) [inline src/app/components/source-graphs/source-tooltip/source-tooltip.component.ts]: because the height doesn't change we can set it in `ngAfterViewInit`, to avoid the constant check

**Review by herkulano — CHANGES_REQUESTED** [review]

File: src/app/components/source-graphs/source-graphs.component.ts [hunk 4]
```diff
@@ -31,6 +31,7 @@ export class SourceGraphsComponent implements OnInit {
   tooltipX = 0
   tooltipY = 0
   tooltipShow = 0 // 0 hide | 1 show
+  tooltipOffsetY = 30
```
Comment (herkulano) [inline src/app/components/source-graphs/source-graphs.component.ts]: you could use a CSS padding instead like we did for the width

**Review by herkulano — APPROVED** [review]
